# Generated by Django 4.1.3 on 2023-07-22 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ('-date_created',)},
        ),
    ]
