# Generated by Django 4.1.3 on 2023-12-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_postcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='accuracy',
            field=models.CharField(default='false', max_length=100),
        ),
    ]
