# Generated by Django 4.1.3 on 2023-12-02 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_blogmodel_accuracy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='accuracy',
            field=models.TextField(default='false'),
        ),
    ]
