# Generated by Django 4.1.3 on 2023-12-04 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0006_blogmodel_gender_alter_blogmodel_accuracy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='gender',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='category',
            field=models.CharField(choices=[('sport', 'Sport'), ('politics', 'Politics'), ('economics', 'Economics'), ('weather', 'Weather'), ('health', 'Health'), ('education', 'Education')], default='general', max_length=10),
        ),
    ]
