# Generated by Django 4.1.3 on 2023-12-11 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
